### ISSUE TITLE
make run error 

### ISSUE THREAD

**Issue by wgngoo** [busser/label-operator#1]
Reference documentation , make run error：
documentation ： https://mp.weixin.qq.com/s/QMjqs4Atb_I-T_objt0gGQ
error：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1356f0b]
goroutine 310 [running]:
github.com/go-logr/logr.Logger.WithValues(...)
	/root/gopath/pkg/mod/github.com/go-logr/logr@v1.2.0/logr.go:283
github.com/wgngoo/pod-label-operator/controllers.(*PodReconciler).Reconcile(0xc0006597a0, {0x1834438, 0xc000871770}, {{{0xc000607f20, 0xb}, {0xc000607f00, 0x10}}})
	/home/vagrant/kubernetes/pod-label-operator/controllers/pod_controller.go:49 +0x10b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00030a2c0, {0x1834438, 0xc0008716b0}, {{{0xc000607f20, 0x1579ca0}, {0xc000607f00, 0x415334}}})
	/root/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00030a2c0, {0x1834390, 0xc000507940}, {0x14d1f80, 0xc0002c69c0})
	/root/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00030a2c0, {0x1834390, 0xc000507940})
	/root/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/root/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/root/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x357

**Comment by semihbkgr** [comment]
Did you set Log field in PodReconciler struct? @wgngoo 

[main.go](/busser/label-operator/blob/main/main.go)

```go
if err = (&controllers.PodReconciler{
    Client: mgr.GetClient(),
    Log:    ctrl.Log.WithName("controllers").WithName("Pod"),
    Scheme: mgr.GetScheme(),
}).SetupWithManager(mgr); err != nil {
    setupLog.Error(err, "unable to create controller", "controller", "Pod")
    os.Exit(1)
}
```
